#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Apr 18 10:43:37 2018

@author: test
"""
import os

# .bmp files directory
path1='/home/test/Public/dataset/20180417/final_data/20180419_update/img_test/'

# .xml files dirctory
path2='/home/test/Public/dataset/20180417/final_data/20180419_update/xml_test/'

files= os.listdir(path2)
i=601

_list=[]
_dic={}

for file in files:
    os.rename(path2+file,path2+"A"+'{:04d}'.format(i)+".xml")
    os.rename(path1+file.split(".")[0]+".jpg",path1+"A"+'{:04d}'.format(i)+".jpg")
    _list.append([file,"A"+'{:04d}'.format(i)])
    _dic.update({file:"A"+'{:04d}'.format(i)})
    i=i+1

# write a list into .txt file
with open("files_change_record.txt",mode="a") as file:
    for item in _list:
        file.write("%s\n" % item)
        
        